select distinct c.data_type from information_schema.columns c;


SELECT table_name, column_name, data_type, udt_name
    FROM information_schema.columns c 
    WHERE c.column_name in  ('Id');

   
   SELECT table_name, column_name, data_type, udt_name, *
    FROM information_schema.columns c 
    WHERE c.table_name in  ('SecurityMaster');
   
    
    AND c.column_name not in  (SELECT column_name
							    FROM information_schema.columns c 
							    WHERE c.table_name NOT LIKE 'pg%' and c.table_name in  ('MutableAsset'))
    
							    
							    
							    
SELECT p."Id", p."AccountId", p."AccountNumber", p."AcquisitionCost", p."AcquisitionDate", p."AssetClassLevel1", p."AssetClassLevel2", p."AssetClassLevel3", p."AssetDescriptionBrief", p."AssetDescriptionDetailed", p."AssetFriendlyName", p."AssetLegalName", p."AssetLocation", p."AutoMake", p."AutoModel", p."AutoYear", p."BaseCurrencyCode", p."BaseCurrencyDayEndAccruedDividendIncome", p."BaseCurrencyDayEndAccruedInterestIncome", p."BaseCurrencyDayEndAccruedOtherIncome", p."BaseCurrencyDayEndPrice", p."BaseCurrencyDayEndUnrealizedFXAccruedIncome", p."BaseCurrencyDayEndUnrealizedFXPriceGainLoss", p."BaseCurrencyDayEndUnrealizedPriceGainLoss", p."BaseCurrencyEndMarketValue", p."BaseCurrencyITDNetProfitLoss", p."BaseCurrencyITDRealizedDividendIncome", p."BaseCurrencyITDRealizedInterestExpense", p."BaseCurrencyITDRealizedInterestIncome", p."BaseCurrencyITDRealizedOtherExpense", p."BaseCurrencyITDRealizedOtherIncome", p."BaseCurrencyITDRealizedTradingGainLoss", p."BaseCurrencyOriginalCost", p."Classifications", p."CountryOfAssetLocation", p."DiscountRate", p."ExpectedFutureLiquidationDate", p."ExpectedFutureValue", p."ExternalSystemKeyAccounting", p."ExternalSystemKeyCRM", p."ExternalSystemKeyCompliance", p."ExternalSystemKeyCustody", p."ExternalSystemKeyInsurance", p."ExternalSystemKeyOnboarding", p."ExternalSystemKeyPerformance", p."ExternalSystemKeyPlanning", p."ExternalSystemKeyPortfolioManagement", p."ExternalSystemKeyRegulatory", p."ExternalSystemKeyRisk", p."ExternalSystemKeyTrading", p."FinancialInstitutionName", p."FitchRating", p."FundAdministratorName", p."FundAdvisorCompanyName", p."FutureIncomeEndDate", p."FutureIncomePeriodicity", p."FutureIncomeStartDate", p."HasAlert", p."InterestRatePaid", p."InterestRatePayable", p."IsExcludedFromNetWorth", p."IssuerName", p."LocalCurrencyEndMarketValue", p."LocalCurrencyITDChangePrice", p."LocalCurrencyPrice", p."MoodysRating", p."Name", p."NasdaqEarliestFinancialQuarter", p."NasdaqEarliestPriceDate", p."NasdaqLatestFinancialQuarter", p."NasdaqMostRecentPriceDate", p."PerPeriodFutureIncome", p."PerUnitAcquisitionCost", p."PriceDate", p."PriceFactor", p."PricingVendorPrimary", p."PrincipalBalance", p."RecordContext", p."RecordState", p."ReferenceDates", p."ReferenceNumbers", p."RegionOfRisk", p."RelatedPartyAddress", p."RelatedPartyEmail", p."RelatedPartyName", p."RelatedPartyPhone", p."RelatedTickers", p."SICCode", p."SICIndustryTitle", p."SICOffice", p."SPRating", p."ShortName", p."StatusOfListing", p."SymCountryOfTrading", p."SymCusip", p."SymIsin", p."SymMorningstarFundId", p."SymOtherSymbols", p."SymSedol", p."SymTicker", p."TaxTreatmentMethod", p."UnitsHeld"
    FROM metadata."PrivateAsset" AS p
    
    
    
SELECT t."AccountId", a."Id" IS NULL,  a."AccountNumber", --, a."AccountOwnerName", a."AccountOwnerNameJoint", --a."AccountTypes", a."AdvisorName", a."AdvisorStrategyDescription", a."AdvisoryTeamName", a."AnnualManagementFeePercent", a."AssetAllocationDescription", a."AssetAllocationName", a."BaseCurrency", a."BulletCount", a."BulletFrequency", a."BulletWithdrawlAmount", a."BusinessUnitLevel1", a."BusinessUnitLevel2", a."BusinessUnitLevel3", a."BusinessUnitLevel4", a."BusinessUnitLevel5", a."Classifications", a."CloseReason", a."Comments", a."CustodyCity", a."CustodyCountry", a."CustodyRegion", a."CustodyState", a."DecumulationStartDate", a."Description", a."DiscretionaryTermStartDate", a."ExpectedDecumulationEndDate", a."ExpectedGrowthRateToTargetMarketValue", a."ExpectedMonthlyContributionToTargetMarketValue", a."ExternalSystemKeyAccounting", a."ExternalSystemKeyCompliance", a."ExternalSystemKeyCRM", a."ExternalSystemKeyCustody", a."ExternalSystemKeyInsurance", a."ExternalSystemKeyOnboarding", a."ExternalSystemKeyPerformance", a."ExternalSystemKeyPlanning", a."ExternalSystemKeyPortfolioManagement", a."ExternalSystemKeyRegulatory", a."ExternalSystemKeyRisk", a."ExternalSystemKeyTrading", a."GeneralLedgerType", a."HasNewAlerts", a."HasNewDocuments", a."Id", a."InflationRate", a."InitialBulletWithdrawlDate", a."InstitutionName1", a."InstitutionName2", a."IsAdvisorDefaultAccount", a."IsClosed", a."IsDiscretionary", a."IsERISA", a."IsExcludedFromNetWorthReporting", a."IsExcludedFromRegulatoryReporting", a."IsHiddenFromAdvisor", a."IsHiddenFromOwner", a."IsMarginApproved", a."IsMasterAccount", a."IsNIGO", a."IsOptionsApproved", a."ISOTimeZone", a."IsOwnerDefaultAccount", a."IsSubAccount", a."LegalName", a."LongName", a."LotReliefMethodDefault", a."ManagerFriendlyName", a."ManagerStrategyDescription", a."ModelPortfolioDescription", a."ModelPortfolioName", a."OnboardingStages", a."OwnerCountryOfDomicile", a."OwnerFiscalYearStartDate", a."OwnerFriendlyName", a."PreferredSecurityIdentifier", a."ReportingCurrency", a."ShortName", a."Statuses", a."StatusNote", a."StrategyDescription", a."SubBusinessUnitLevel1", a."SubBusinessUnitLevel2", a."SubBusinessUnitLevel3", a."SubBusinessUnitLevel4", a."SubBusinessUnitLevel5", a."TargetDescription", a."TargetMarketValue", a."TargetMarketValueDate", a."TaxTreatmentTypes", a."ThirdPartyConsultantNames", a."UserAccessId", a."IsPrivateAsset", a."NetWorthMultiplier", t."AccountNumber", 
t."SymTicker", t."AcquisitionCost", t."AcquisitionDate", t."UnitsHeld", t."RecordContext", t."CreatedBy", t."CreatedOn", t."UpdatedBy", t."UpdatedOn"  --t."AssetClassLevel1", t."AssetClassLevel2", t."AssetClassLevel3", t."AssetDescriptionBrief", t."AssetDescriptionDetailed", t."AssetFriendlyName", t."AssetLegalName", t."AutoMake", t."AutoModel", t."AutoYear", t."BaseCurrencyCode", t."BaseCurrencyDayEndAccruedDividendIncome", t."BaseCurrencyDayEndAccruedInterestIncome", t."BaseCurrencyDayEndAccruedOtherIncome", t."BaseCurrencyDayEndPrice", t."BaseCurrencyDayEndUnrealizedFXAccruedIncome", t."BaseCurrencyDayEndUnrealizedFXPriceGainLoss", t."BaseCurrencyDayEndUnrealizedPriceGainLoss", t."BaseCurrencyEndMarketValue", t."BaseCurrencyITDNetProfitLoss", t."BaseCurrencyITDRealizedDividendIncome", t."BaseCurrencyITDRealizedInterestExpense", t."BaseCurrencyITDRealizedInterestIncome", t."BaseCurrencyITDRealizedOtherExpense", t."BaseCurrencyITDRealizedOtherIncome", t."BaseCurrencyITDRealizedTradingGainLoss", t."BaseCurrencyOriginalCost", t."Classifications", t."CountryOfAssetLocation", t."DiscountRate", t."ExpectedFutureLiquidationDate", t."ExpectedFutureValue", t."ExternalSystemKeyAccounting", t."ExternalSystemKeyCompliance", t."ExternalSystemKeyCRM", t."ExternalSystemKeyCustody", t."ExternalSystemKeyInsurance", t."ExternalSystemKeyOnboarding", t."ExternalSystemKeyPerformance", t."ExternalSystemKeyPlanning", t."ExternalSystemKeyPortfolioManagement", t."ExternalSystemKeyRegulatory", t."ExternalSystemKeyRisk", t."ExternalSystemKeyTrading", t."FinancialInstitutionName", t."FitchRating", t."FundAdministratorName", t."FundAdvisorCompanyName", t."FutureIncomeEndDate", t."FutureIncomePeriodicity", t."FutureIncomeStartDate", t."HasAlert", t."Id", t."InterestRatePaid", t."InterestRatePayable", t."IsExcludedFromNetWorth", t."IssuerName", t."LocalCurrencyEndMarketValue", t."LocalCurrencyITDChangePrice", t."LocalCurrencyPrice", t."MoodysRating", t."Name", t."NasdaqEarliestFinancialQuarter", t."NasdaqEarliestPriceDate", t."NasdaqLatestFinancialQuarter", t."NasdaqMostRecentPriceDate", t."PerPeriodFutureIncome", t."PerUnitAcquisitionCost", t."PriceDate", t."PriceFactor", t."PricingVendorPrimary", t."PrincipalBalance", t."RecordState", t."ReferenceDates", t."ReferenceNumbers", t."RegionOfRisk", t."RelatedPartyAddress", t."RelatedPartyEmail", t."RelatedPartyName", t."RelatedPartyPhone", t."RelatedTickers", t."ShortName", t."SICCode", t."SICIndustryTitle", t."SICOffice", t."SPRating", t."StatusOfListing", t."SymCountryOfTrading", t."SymCusip", t."SymIsin", t."SymMorningstarFundId", t."SymOtherSymbols", t."SymSedol", t."SymTicker", t."TaxTreatmentMethod", t."UnitsHeld", t."AssetLocation", t."RecordContext"
FROM (
    SELECT p."Id", p."AccountId", p."AccountNumber", p."AcquisitionCost", p."CreatedBy", p."CreatedOn",  p."UpdatedBy", p."UpdatedOn", p."AcquisitionDate", p."AssetClassLevel1", p."AssetClassLevel2", p."AssetClassLevel3", p."AssetDescriptionBrief", p."AssetDescriptionDetailed", p."AssetFriendlyName", p."AssetLegalName", p."AssetLocation", p."AutoMake", p."AutoModel", p."AutoYear", p."BaseCurrencyCode", p."BaseCurrencyDayEndAccruedDividendIncome", p."BaseCurrencyDayEndAccruedInterestIncome", p."BaseCurrencyDayEndAccruedOtherIncome", p."BaseCurrencyDayEndPrice", p."BaseCurrencyDayEndUnrealizedFXAccruedIncome", p."BaseCurrencyDayEndUnrealizedFXPriceGainLoss", p."BaseCurrencyDayEndUnrealizedPriceGainLoss", p."BaseCurrencyEndMarketValue", p."BaseCurrencyITDNetProfitLoss", p."BaseCurrencyITDRealizedDividendIncome", p."BaseCurrencyITDRealizedInterestExpense", p."BaseCurrencyITDRealizedInterestIncome", p."BaseCurrencyITDRealizedOtherExpense", p."BaseCurrencyITDRealizedOtherIncome", p."BaseCurrencyITDRealizedTradingGainLoss", p."BaseCurrencyOriginalCost", p."Classifications", p."CountryOfAssetLocation", p."DiscountRate", p."ExpectedFutureLiquidationDate", p."ExpectedFutureValue", p."ExternalSystemKeyAccounting", p."ExternalSystemKeyCRM", p."ExternalSystemKeyCompliance", p."ExternalSystemKeyCustody", p."ExternalSystemKeyInsurance", p."ExternalSystemKeyOnboarding", p."ExternalSystemKeyPerformance", p."ExternalSystemKeyPlanning", p."ExternalSystemKeyPortfolioManagement", p."ExternalSystemKeyRegulatory", p."ExternalSystemKeyRisk", p."ExternalSystemKeyTrading", p."FinancialInstitutionName", p."FitchRating", p."FundAdministratorName", p."FundAdvisorCompanyName", p."FutureIncomeEndDate", p."FutureIncomePeriodicity", p."FutureIncomeStartDate", p."HasAlert", p."InterestRatePaid", p."InterestRatePayable", p."IsExcludedFromNetWorth", p."IssuerName", p."LocalCurrencyEndMarketValue", p."LocalCurrencyITDChangePrice", p."LocalCurrencyPrice", p."MoodysRating", p."Name", p."NasdaqEarliestFinancialQuarter", p."NasdaqEarliestPriceDate", p."NasdaqLatestFinancialQuarter", p."NasdaqMostRecentPriceDate", p."PerPeriodFutureIncome", p."PerUnitAcquisitionCost", p."PriceDate", p."PriceFactor", p."PricingVendorPrimary", p."PrincipalBalance", p."RecordContext", p."RecordState", p."ReferenceDates", p."ReferenceNumbers", p."RegionOfRisk", p."RelatedPartyAddress", p."RelatedPartyEmail", p."RelatedPartyName", p."RelatedPartyPhone", p."RelatedTickers", p."SICCode", p."SICIndustryTitle", p."SICOffice", p."SPRating", p."ShortName", p."StatusOfListing", p."SymCountryOfTrading", p."SymCusip", p."SymIsin", p."SymMorningstarFundId", p."SymOtherSymbols", p."SymSedol", p."SymTicker", p."TaxTreatmentMethod", p."UnitsHeld"
    FROM metadata."PrivateAsset" AS p
    --WHERE p."SymTicker" = 'NVDA' --AND p."CreatedBy" = @__req_UserId_1
) AS t
LEFT JOIN metadata."Account" AS a ON t."AccountId" = a."Id";

delete from metadata."PrivateAsset" p where p."AcquisitionDate" is null;


delete from metadata."PrivateAsset" ;