version: '3'

services:
  postgres:
    build: ./postgres
    container_name: mytech-postgres
    environment:
      POSTGRES_USER: mytech
      POSTGRES_PASSWORD: mytech
      POSTGRES_DB: mytech
    ports:
      - "4009:4009"
    volumes:
      - /Volumes/data:/var/lib/postgresql/data
      - ./initdb:/docker-entrypoint-initdb.d  # Add this line

  quart:
    build: .
    container_name: mytech-quart
    environment:
      - POSTGRES_USER=mytech
      - POSTGRES_PASSWORD=mytech
      - POSTGRES_DB=mytech
      - POSTGRES_HOST=postgres
    ports:
      - "4008:4008"
    volumes:
      - .:/app  # Maps the current directory to /app in the container
    depends_on:
      - postgres

  streamlit:
    build: .
    container_name: mytech-streamlit
    environment:
      - POSTGRES_USER=mytech
      - POSTGRES_PASSWORD=mytech
      - POSTGRES_DB=mytech
      - POSTGRES_HOST=postgres
    ports:
      - "4010:4010"
    volumes:
      - .:/app  # Maps the current directory to /app in the container
    depends_on:
      - postgres