version: '3.8'

services:
  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    ports:
      - "8501:8501"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1

  # flask:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.flask
  #   ports:
  #     - "5000:5000"
  #   volumes:
  #     - .:/app
  #   environment:
  #     - FLASK_APP=flask_app.py
  #     - FLASK_RUN_HOST=0.0.0.0
  #     - PYTHONUNBUFFERED=1

  # ollama:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile.ollama
  #   ports:
  #     - "8000:8000"
  #   volumes:
  #     - .:/app
  #   environment:
  #     - PYTHONUNBUFFERED=1